### ISSUE TITLE
Action Board- After approving or denying an exception, it does not auto select another item. In the current program it selects the one at the top, if if you have scrolled down a ways, would like to see it select the next one in the list from the one you were resolving.

### ISSUE THREAD

**Issue by johnmurphy01** [gatewayapps/ims-feedback#460]
Version: 0.3.1 
 User: JAMES BYRD (jim.byrd@nucor-yamato.com)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [gatewayapps/nys-scheduling](https://github.com/gatewayapps/nys-scheduling/issues/383)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/103380699-51615e80-4aaf-11eb-997f-304270d3e8a5.png)

**Comment by jimbyrd** [comment]
After approving Bruce Baird, it still shows Bruce selected, but Tripods info
