### ISSUE TITLE
Main Screen (monthly view) I am not able to de-select myself from showing up on the calendar. The checkbox will uncheck, but I stay on the calendar. 

### ISSUE THREAD

**Issue by johnmurphy01** [gatewayapps/ims-feedback#464]
Version: 0.3.1 
 User: JAMES BYRD (jim.byrd@nucor-yamato.com)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [gatewayapps/nys-scheduling](https://github.com/gatewayapps/nys-scheduling/issues/387)

**Comment by jimbyrd** [comment]
this is related to **#463** - Main Screen (monthly view) screen loaded my crew was selected (170E), I click the 170E check box, get a 'prohibition sign' cursor for a few seconds after I click it, all names do disappear from calendar, but '1FN/E' remains checked. Can click it and it will shut off. Then can click individual boxes to turn some on. 
If I leave the '1FN/E' box checked I can turn myself on and off, but If I de-select '1FN/E', I can not, until.... I click the clear button, then it all appears to work as it soon, until I navigate away and back to the screen.
