### ISSUE TITLE
Setup:Schedules - Click to Edit D4 which shows 7a - 3p, but pop-up shows 1:am to 9:am and preview is wrong.

### ISSUE THREAD

**Issue by johnmurphy01** [gatewayapps/ims-feedback#466]
Version: 0.3.1 
 User: JAMES BYRD (jim.byrd@nucor-yamato.com)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/102407493-d299fb00-3fb1-11eb-930f-c239c3e2a21c.png)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [gatewayapps/nys-scheduling](https://github.com/gatewayapps/nys-scheduling/issues/389)
