### ISSUE TITLE
Calendar:Monthly view - clicked on Jan 4, got request off pop-up. left start/end date as the appeared 1/04/2021 on both, left reason as Vac day. Added comments to both comment boxes and clicked save. Nothing happened. Tried several times. same result. Clicked cancel, it did cancel. made changes to dates and reason, still nothing for save.

### ISSUE THREAD

**Issue by johnmurphy01** [gatewayapps/ims-feedback#469]
Version: 0.3.1 
 User: JAMES BYRD (jim.byrd@nucor-yamato.com)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/102409862-599ca280-3fb5-11eb-9dc0-acc41aa0f439.png)

**Comment by jimbyrd** [comment]
Noticed the arrow on top right of Jan 4, clicked and went to larger screen for 'Add Exception' when I click save, I get "Cannot read property 'code' of undefined"

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/102410507-4211e980-3fb6-11eb-984c-24894cce82c0.png)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [gatewayapps/nys-scheduling](https://github.com/gatewayapps/nys-scheduling/issues/393)

**Comment by johnmurphy01** [comment]
@jimbyrd can you try this again with the latest version? I can only login as System Administrator and so I can't request off for you in staging. Wondering if this was fixed when we fixed the issues with the calendar schedules being messed up
