### ISSUE TITLE
Calendar:Monthly view - for off days, use same color (grey) as bar, not black 

### ISSUE THREAD

**Issue by johnmurphy01** [gatewayapps/ims-feedback#470]
Version: 0.3.1 
 User: JAMES BYRD (jim.byrd@nucor-yamato.com)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/102410142-bb5d0c80-3fb5-11eb-84a5-0204d96565df.png)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [gatewayapps/nys-scheduling](https://github.com/gatewayapps/nys-scheduling/issues/394)
