### ISSUE TITLE
I apply a schedule to my position, either D3 or D4 both appear to apply but on the schedule it shows Sun-Thurs, should be Mon-Fri.

### ISSUE THREAD

**Issue by johnmurphy01** [gatewayapps/ims-feedback#471]
Version: 0.4.1 
 User: JAMES BYRD (jim.byrd@nucor-yamato.com)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/102790948-e22b9200-436b-11eb-8d8e-d64f3e729f8c.png)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/102791021-fcfe0680-436b-11eb-8a95-43a7a0e9ff9b.png)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [gatewayapps/nys-scheduling](https://github.com/gatewayapps/nys-scheduling/issues/410)

**Comment by johnmurphy01** [comment]
@jimbyrd looking at this now.
