### ISSUE TITLE
Schedule under Setup/Users is D3-OFF-N2-OFF-OFF-OFF-OFF-OFF-D3-OFF, but in positions it is D3

### ISSUE THREAD

**Issue by johnmurphy01** [gatewayapps/ims-feedback#472]
Version: 0.5.0 
 User: JAMES BYRD (jim.byrd@nucor-yamato.com)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/102803887-96ceaf00-437e-11eb-8942-902b7be09d27.png)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/102803960-b1a12380-437e-11eb-8222-3f95643d9136.png)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/102804211-0ba1e900-437f-11eb-9dbd-560b27de18c5.png)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [gatewayapps/nys-scheduling](https://github.com/gatewayapps/nys-scheduling/issues/413)
