### ISSUE TITLE
We when you delete a user from user list, you do not get a "are you sure", it just deletes.

### ISSUE THREAD

**Issue by johnmurphy01** [gatewayapps/ims-feedback#476]
Version: 0.6.2 
 User: JAMES BYRD (jim.byrd@nucor-yamato.com)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/103380217-d51a4b80-4aad-11eb-82f9-f5d7f71f95df.png)

**Comment by jimbyrd** [comment]
Screenshot is from current program

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [gatewayapps/nys-scheduling](https://github.com/gatewayapps/nys-scheduling/issues/425)
