### ISSUE TITLE
Action Board - approve/Deny - you get pop up for Supv comments, if you add comments. it works, and get toast, but if no comment, it get closes popup and doesn't work, no toast

### ISSUE THREAD

**Issue by johnmurphy01** [gatewayapps/ims-feedback#477]
Version: 0.6.2 
 User: JAMES BYRD (jim.byrd@nucor-yamato.com)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/103381173-9f2a9680-4ab0-11eb-9a6b-ea4345c144bb.png)

**Comment by jimbyrd** [comment]
Approve/Deny all, if you dont add comment, you get error

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/103381230-ce410800-4ab0-11eb-9c75-2bf970925d3b.png)

**Comment by jimbyrd** [comment]
Same with comment

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [gatewayapps/nys-scheduling](https://github.com/gatewayapps/nys-scheduling/issues/426)
