### ISSUE TITLE
Action board - Coverage person does not show that they are on call

### ISSUE THREAD

**Issue by johnmurphy01** [gatewayapps/ims-feedback#478]
Version: 0.6.3 
 User: JAMES BYRD (jim.byrd@nucor-yamato.com)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/103422400-d8254280-4b66-11eb-8a26-be203d44c6df.png)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/103422409-e8d5b880-4b66-11eb-9781-747221c50425.png)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/103422429-fee37900-4b66-11eb-88d2-be451a94f0c2.png)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [gatewayapps/nys-scheduling](https://github.com/gatewayapps/nys-scheduling/issues/430)
