### ISSUE TITLE
I double click on a day to request vac. have a refresh continuously circling to the right of 'Requires Coverage'. Select reason, add comment, but not allowed to click 'Save' 

### ISSUE THREAD

**Issue by johnmurphy01** [gatewayapps/ims-feedback#481]
Version: 0.8.0 
 User: JAMES BYRD (jim.byrd@nucor-yamato.com)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/104352250-0cd0bc80-54cc-11eb-81e3-93f11d6b2602.png)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [gatewayapps/nys-scheduling](https://github.com/gatewayapps/nys-scheduling/issues/448)
