### ISSUE TITLE
Click on day to request off, does not let me type in either comment box, does allow me to click save, and it does complete and change the day

### ISSUE THREAD

**Issue by johnmurphy01** [gatewayapps/ims-feedback#482]
Version: 0.8.0 
 User: JAMES BYRD (jim.byrd@nucor-yamato.com)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/104352523-63d69180-54cc-11eb-9dcc-72c303b2dd15.png)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [gatewayapps/nys-scheduling](https://github.com/gatewayapps/nys-scheduling/issues/449)
