### ISSUE TITLE
On the list page, all filters appear to work, except location. Unless, if I pick 'Rollmill 1' when entering and choosing a filter one up from that "Rollmill" does get the nodes below it.

### ISSUE THREAD

**Issue by johnmurphy01** [gatewayapps/ims-feedback#488]
Version: 0.6.0 

 User: Jim Byrd(jim.byrd@nucor-yamato.com)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/115266215-a3310180-a0fd-11eb-8ee9-4d9eb4f47410.png)

**Comment by jimbyrd** [comment]
![image](https://user-images.githubusercontent.com/28160043/115266327-bb088580-a0fd-11eb-91b0-831cd14c4fea.png)
